[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { version = "1.3.0", features = ["unstable"] }
include_directory = "*"
bevy_math = "*"
log = "0.4"
