// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::st_asset_type::StAsset;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `asset`.
///
/// Obtain a handle from the [`AssetTableAccess::asset`] method on [`super::RemoteTables`],
/// like `ctx.db.asset()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asset().on_insert(...)`.
pub struct AssetTableHandle<'ctx> {
    imp: __sdk::TableHandle<StAsset>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `asset`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AssetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AssetTableHandle`], which mediates access to the table `asset`.
    fn asset(&self) -> AssetTableHandle<'_>;
}

impl AssetTableAccess for super::RemoteTables {
    fn asset(&self) -> AssetTableHandle<'_> {
        AssetTableHandle {
            imp: self.imp.get_table::<StAsset>("asset"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AssetInsertCallbackId(__sdk::CallbackId);
pub struct AssetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AssetTableHandle<'ctx> {
    type Row = StAsset;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StAsset> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AssetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AssetInsertCallbackId {
        AssetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AssetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AssetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AssetDeleteCallbackId {
        AssetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AssetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StAsset>("asset");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct AssetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AssetTableHandle<'ctx> {
    type UpdateCallbackId = AssetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AssetUpdateCallbackId {
        AssetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AssetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StAsset>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StAsset>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `asset`,
/// which allows point queries on the field of the same name
/// via the [`AssetIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asset().id().find(...)`.
pub struct AssetIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StAsset, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AssetTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `asset`.
    pub fn id(&self) -> AssetIdUnique<'ctx> {
        AssetIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AssetIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StAsset> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `asset`,
/// which allows point queries on the field of the same name
/// via the [`AssetNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asset().name().find(...)`.
pub struct AssetNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StAsset, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AssetTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `asset`.
    pub fn name(&self) -> AssetNameUnique<'ctx> {
        AssetNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AssetNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<StAsset> {
        self.imp.find(col_val)
    }
}
