// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::chunk_type::Chunk;
use super::st_i_vec_3_type::StIVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk`.
///
/// Obtain a handle from the [`ChunkTableAccess::chunk`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk().on_insert(...)`.
pub struct ChunkTableHandle<'ctx> {
    imp: __sdk::TableHandle<Chunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkTableHandle`], which mediates access to the table `chunk`.
    fn chunk(&self) -> ChunkTableHandle<'_>;
}

impl ChunkTableAccess for super::RemoteTables {
    fn chunk(&self) -> ChunkTableHandle<'_> {
        ChunkTableHandle {
            imp: self.imp.get_table::<Chunk>("chunk"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkInsertCallbackId(__sdk::CallbackId);
pub struct ChunkDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChunkTableHandle<'ctx> {
    type Row = Chunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Chunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkInsertCallbackId {
        ChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkDeleteCallbackId {
        ChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Chunk>("chunk");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Chunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Chunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
