// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::chunk_schedule_type::ChunkSchedule;
use super::st_i_vec_3_type::StIVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk_schedule`.
///
/// Obtain a handle from the [`ChunkScheduleTableAccess::chunk_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_schedule().on_insert(...)`.
pub struct ChunkScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChunkSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkScheduleTableHandle`], which mediates access to the table `chunk_schedule`.
    fn chunk_schedule(&self) -> ChunkScheduleTableHandle<'_>;
}

impl ChunkScheduleTableAccess for super::RemoteTables {
    fn chunk_schedule(&self) -> ChunkScheduleTableHandle<'_> {
        ChunkScheduleTableHandle {
            imp: self.imp.get_table::<ChunkSchedule>("chunk_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkScheduleInsertCallbackId(__sdk::CallbackId);
pub struct ChunkScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChunkScheduleTableHandle<'ctx> {
    type Row = ChunkSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkScheduleInsertCallbackId {
        ChunkScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkScheduleDeleteCallbackId {
        ChunkScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChunkSchedule>("chunk_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct ChunkScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkScheduleTableHandle<'ctx> {
    type UpdateCallbackId = ChunkScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkScheduleUpdateCallbackId {
        ChunkScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ChunkSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChunkSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `chunk_schedule`,
/// which allows point queries on the field of the same name
/// via the [`ChunkScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_schedule().scheduled_id().find(...)`.
pub struct ChunkScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChunkSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChunkScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `chunk_schedule`.
    pub fn scheduled_id(&self) -> ChunkScheduleScheduledIdUnique<'ctx> {
        ChunkScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChunkScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ChunkSchedule> {
        self.imp.find(col_val)
    }
}
