// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreatePlayerArgs {
    pub name: String,
}

impl From<CreatePlayerArgs> for super::Reducer {
    fn from(args: CreatePlayerArgs) -> Self {
        Self::CreatePlayer { name: args.name }
    }
}

impl __sdk::InModule for CreatePlayerArgs {
    type Module = super::RemoteModule;
}

pub struct CreatePlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_player {
    /// Request that the remote module invoke the reducer `create_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_player`] callbacks.
    fn create_player(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreatePlayerCallbackId`] can be passed to [`Self::remove_on_create_player`]
    /// to cancel the callback.
    fn on_create_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreatePlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_player`],
    /// causing it not to run in the future.
    fn remove_on_create_player(&self, callback: CreatePlayerCallbackId);
}

impl create_player for super::RemoteReducers {
    fn create_player(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_player", CreatePlayerArgs { name })
    }
    fn on_create_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreatePlayerCallbackId {
        CreatePlayerCallbackId(self.imp.on_reducer(
            "create_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreatePlayer { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_create_player(&self, callback: CreatePlayerCallbackId) {
        self.imp.remove_on_reducer("create_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_player {
    /// Set the call-reducer flags for the reducer `create_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_player for super::SetReducerFlags {
    fn create_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_player", flags);
    }
}
