// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::mesh_build_schedule_type::MeshBuildSchedule;
use super::st_i_vec_3_type::StIVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mesher_schedule`.
///
/// Obtain a handle from the [`MesherScheduleTableAccess::mesher_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.mesher_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mesher_schedule().on_insert(...)`.
pub struct MesherScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<MeshBuildSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mesher_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MesherScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MesherScheduleTableHandle`], which mediates access to the table `mesher_schedule`.
    fn mesher_schedule(&self) -> MesherScheduleTableHandle<'_>;
}

impl MesherScheduleTableAccess for super::RemoteTables {
    fn mesher_schedule(&self) -> MesherScheduleTableHandle<'_> {
        MesherScheduleTableHandle {
            imp: self.imp.get_table::<MeshBuildSchedule>("mesher_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MesherScheduleInsertCallbackId(__sdk::CallbackId);
pub struct MesherScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MesherScheduleTableHandle<'ctx> {
    type Row = MeshBuildSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MeshBuildSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MesherScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MesherScheduleInsertCallbackId {
        MesherScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MesherScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MesherScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MesherScheduleDeleteCallbackId {
        MesherScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MesherScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MeshBuildSchedule>("mesher_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct MesherScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MesherScheduleTableHandle<'ctx> {
    type UpdateCallbackId = MesherScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MesherScheduleUpdateCallbackId {
        MesherScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MesherScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MeshBuildSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MeshBuildSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `mesher_schedule`,
/// which allows point queries on the field of the same name
/// via the [`MesherScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mesher_schedule().scheduled_id().find(...)`.
pub struct MesherScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MeshBuildSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MesherScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `mesher_schedule`.
    pub fn scheduled_id(&self) -> MesherScheduleScheduledIdUnique<'ctx> {
        MesherScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MesherScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MeshBuildSchedule> {
        self.imp.find(col_val)
    }
}
