// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::mesh_type::Mesh;
use super::st_i_vec_3_type::StIVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mesh`.
///
/// Obtain a handle from the [`MeshTableAccess::mesh`] method on [`super::RemoteTables`],
/// like `ctx.db.mesh()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mesh().on_insert(...)`.
pub struct MeshTableHandle<'ctx> {
    imp: __sdk::TableHandle<Mesh>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mesh`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MeshTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MeshTableHandle`], which mediates access to the table `mesh`.
    fn mesh(&self) -> MeshTableHandle<'_>;
}

impl MeshTableAccess for super::RemoteTables {
    fn mesh(&self) -> MeshTableHandle<'_> {
        MeshTableHandle {
            imp: self.imp.get_table::<Mesh>("mesh"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MeshInsertCallbackId(__sdk::CallbackId);
pub struct MeshDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MeshTableHandle<'ctx> {
    type Row = Mesh;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Mesh> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MeshInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MeshInsertCallbackId {
        MeshInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MeshInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MeshDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MeshDeleteCallbackId {
        MeshDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MeshDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Mesh>("mesh");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MeshUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MeshTableHandle<'ctx> {
    type UpdateCallbackId = MeshUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MeshUpdateCallbackId {
        MeshUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MeshUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Mesh>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Mesh>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `mesh`,
/// which allows point queries on the field of the same name
/// via the [`MeshIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mesh().id().find(...)`.
pub struct MeshIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Mesh, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MeshTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `mesh`.
    pub fn id(&self) -> MeshIdUnique<'ctx> {
        MeshIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MeshIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Mesh> {
        self.imp.find(col_val)
    }
}
