// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::tasks_schedule_type::TasksSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProceedTasksArgs {
    pub arg: TasksSchedule,
}

impl From<ProceedTasksArgs> for super::Reducer {
    fn from(args: ProceedTasksArgs) -> Self {
        Self::ProceedTasks { arg: args.arg }
    }
}

impl __sdk::InModule for ProceedTasksArgs {
    type Module = super::RemoteModule;
}

pub struct ProceedTasksCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `proceed_tasks`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait proceed_tasks {
    /// Request that the remote module invoke the reducer `proceed_tasks` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_proceed_tasks`] callbacks.
    fn proceed_tasks(&self, arg: TasksSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `proceed_tasks`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ProceedTasksCallbackId`] can be passed to [`Self::remove_on_proceed_tasks`]
    /// to cancel the callback.
    fn on_proceed_tasks(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &TasksSchedule) + Send + 'static,
    ) -> ProceedTasksCallbackId;
    /// Cancel a callback previously registered by [`Self::on_proceed_tasks`],
    /// causing it not to run in the future.
    fn remove_on_proceed_tasks(&self, callback: ProceedTasksCallbackId);
}

impl proceed_tasks for super::RemoteReducers {
    fn proceed_tasks(&self, arg: TasksSchedule) -> __sdk::Result<()> {
        self.imp
            .call_reducer("proceed_tasks", ProceedTasksArgs { arg })
    }
    fn on_proceed_tasks(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &TasksSchedule) + Send + 'static,
    ) -> ProceedTasksCallbackId {
        ProceedTasksCallbackId(self.imp.on_reducer(
            "proceed_tasks",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ProceedTasks { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_proceed_tasks(&self, callback: ProceedTasksCallbackId) {
        self.imp.remove_on_reducer("proceed_tasks", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `proceed_tasks`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_proceed_tasks {
    /// Set the call-reducer flags for the reducer `proceed_tasks` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn proceed_tasks(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_proceed_tasks for super::SetReducerFlags {
    fn proceed_tasks(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("proceed_tasks", flags);
    }
}
