// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mesh_build_schedule_type::MeshBuildSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RunMesherArgs {
    pub arg: MeshBuildSchedule,
}

impl From<RunMesherArgs> for super::Reducer {
    fn from(args: RunMesherArgs) -> Self {
        Self::RunMesher { arg: args.arg }
    }
}

impl __sdk::InModule for RunMesherArgs {
    type Module = super::RemoteModule;
}

pub struct RunMesherCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `run_mesher`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait run_mesher {
    /// Request that the remote module invoke the reducer `run_mesher` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_run_mesher`] callbacks.
    fn run_mesher(&self, arg: MeshBuildSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `run_mesher`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RunMesherCallbackId`] can be passed to [`Self::remove_on_run_mesher`]
    /// to cancel the callback.
    fn on_run_mesher(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &MeshBuildSchedule) + Send + 'static,
    ) -> RunMesherCallbackId;
    /// Cancel a callback previously registered by [`Self::on_run_mesher`],
    /// causing it not to run in the future.
    fn remove_on_run_mesher(&self, callback: RunMesherCallbackId);
}

impl run_mesher for super::RemoteReducers {
    fn run_mesher(&self, arg: MeshBuildSchedule) -> __sdk::Result<()> {
        self.imp.call_reducer("run_mesher", RunMesherArgs { arg })
    }
    fn on_run_mesher(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &MeshBuildSchedule) + Send + 'static,
    ) -> RunMesherCallbackId {
        RunMesherCallbackId(self.imp.on_reducer(
            "run_mesher",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RunMesher { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_run_mesher(&self, callback: RunMesherCallbackId) {
        self.imp.remove_on_reducer("run_mesher", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `run_mesher`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_run_mesher {
    /// Set the call-reducer flags for the reducer `run_mesher` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn run_mesher(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_run_mesher for super::SetReducerFlags {
    fn run_mesher(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("run_mesher", flags);
    }
}
