// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::scanner_type::Scanner;
use super::st_i_vec_3_type::StIVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `scanner`.
///
/// Obtain a handle from the [`ScannerTableAccess::scanner`] method on [`super::RemoteTables`],
/// like `ctx.db.scanner()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scanner().on_insert(...)`.
pub struct ScannerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Scanner>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `scanner`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ScannerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ScannerTableHandle`], which mediates access to the table `scanner`.
    fn scanner(&self) -> ScannerTableHandle<'_>;
}

impl ScannerTableAccess for super::RemoteTables {
    fn scanner(&self) -> ScannerTableHandle<'_> {
        ScannerTableHandle {
            imp: self.imp.get_table::<Scanner>("scanner"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ScannerInsertCallbackId(__sdk::CallbackId);
pub struct ScannerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ScannerTableHandle<'ctx> {
    type Row = Scanner;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Scanner> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ScannerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScannerInsertCallbackId {
        ScannerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ScannerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ScannerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScannerDeleteCallbackId {
        ScannerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ScannerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Scanner>("scanner");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct ScannerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ScannerTableHandle<'ctx> {
    type UpdateCallbackId = ScannerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ScannerUpdateCallbackId {
        ScannerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ScannerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Scanner>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Scanner>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `scanner`,
/// which allows point queries on the field of the same name
/// via the [`ScannerIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scanner().identity().find(...)`.
pub struct ScannerIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Scanner, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ScannerTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `scanner`.
    pub fn identity(&self) -> ScannerIdentityUnique<'ctx> {
        ScannerIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ScannerIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Scanner> {
        self.imp.find(col_val)
    }
}
