// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::tick_schedule_type::TickSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticks`.
///
/// Obtain a handle from the [`TicksTableAccess::ticks`] method on [`super::RemoteTables`],
/// like `ctx.db.ticks()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticks().on_insert(...)`.
pub struct TicksTableHandle<'ctx> {
    imp: __sdk::TableHandle<TickSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticks`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicksTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicksTableHandle`], which mediates access to the table `ticks`.
    fn ticks(&self) -> TicksTableHandle<'_>;
}

impl TicksTableAccess for super::RemoteTables {
    fn ticks(&self) -> TicksTableHandle<'_> {
        TicksTableHandle {
            imp: self.imp.get_table::<TickSchedule>("ticks"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicksInsertCallbackId(__sdk::CallbackId);
pub struct TicksDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicksTableHandle<'ctx> {
    type Row = TickSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TickSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicksInsertCallbackId {
        TicksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicksDeleteCallbackId {
        TicksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TickSchedule>("ticks");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct TicksUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicksTableHandle<'ctx> {
    type UpdateCallbackId = TicksUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicksUpdateCallbackId {
        TicksUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicksUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TickSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TickSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ticks`,
/// which allows point queries on the field of the same name
/// via the [`TicksIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticks().id().find(...)`.
pub struct TicksIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TickSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicksTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticks`.
    pub fn id(&self) -> TicksIdUnique<'ctx> {
        TicksIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicksIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TickSchedule> {
        self.imp.find(col_val)
    }
}
