// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::asset_file_type::AssetFile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `assets`.
///
/// Obtain a handle from the [`AssetsTableAccess::assets`] method on [`super::RemoteTables`],
/// like `ctx.db.assets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.assets().on_insert(...)`.
pub struct AssetsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AssetFile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `assets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AssetsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AssetsTableHandle`], which mediates access to the table `assets`.
    fn assets(&self) -> AssetsTableHandle<'_>;
}

impl AssetsTableAccess for super::RemoteTables {
    fn assets(&self) -> AssetsTableHandle<'_> {
        AssetsTableHandle {
            imp: self.imp.get_table::<AssetFile>("assets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AssetsInsertCallbackId(__sdk::CallbackId);
pub struct AssetsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AssetsTableHandle<'ctx> {
    type Row = AssetFile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AssetFile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AssetsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AssetsInsertCallbackId {
        AssetsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AssetsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AssetsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AssetsDeleteCallbackId {
        AssetsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AssetsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AssetFile>("assets");
    _table.add_unique_constraint::<String>("path", |row| &row.path);
}
pub struct AssetsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AssetsTableHandle<'ctx> {
    type UpdateCallbackId = AssetsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AssetsUpdateCallbackId {
        AssetsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AssetsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AssetFile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AssetFile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `path` unique index on the table `assets`,
/// which allows point queries on the field of the same name
/// via the [`AssetsPathUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.assets().path().find(...)`.
pub struct AssetsPathUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AssetFile, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AssetsTableHandle<'ctx> {
    /// Get a handle on the `path` unique index on the table `assets`.
    pub fn path(&self) -> AssetsPathUnique<'ctx> {
        AssetsPathUnique {
            imp: self.imp.get_unique_constraint::<String>("path"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AssetsPathUnique<'ctx> {
    /// Find the subscribed row whose `path` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AssetFile> {
        self.imp.find(col_val)
    }
}
