// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EditAssetArgs {
    pub path: String,
    pub value: Vec<u8>,
}

impl From<EditAssetArgs> for super::Reducer {
    fn from(args: EditAssetArgs) -> Self {
        Self::EditAsset {
            path: args.path,
            value: args.value,
        }
    }
}

impl __sdk::InModule for EditAssetArgs {
    type Module = super::RemoteModule;
}

pub struct EditAssetCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `edit_asset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait edit_asset {
    /// Request that the remote module invoke the reducer `edit_asset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_edit_asset`] callbacks.
    fn edit_asset(&self, path: String, value: Vec<u8>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `edit_asset`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EditAssetCallbackId`] can be passed to [`Self::remove_on_edit_asset`]
    /// to cancel the callback.
    fn on_edit_asset(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &Vec<u8>) + Send + 'static,
    ) -> EditAssetCallbackId;
    /// Cancel a callback previously registered by [`Self::on_edit_asset`],
    /// causing it not to run in the future.
    fn remove_on_edit_asset(&self, callback: EditAssetCallbackId);
}

impl edit_asset for super::RemoteReducers {
    fn edit_asset(&self, path: String, value: Vec<u8>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("edit_asset", EditAssetArgs { path, value })
    }
    fn on_edit_asset(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &Vec<u8>) + Send + 'static,
    ) -> EditAssetCallbackId {
        EditAssetCallbackId(self.imp.on_reducer(
            "edit_asset",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EditAsset { path, value },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, path, value)
            }),
        ))
    }
    fn remove_on_edit_asset(&self, callback: EditAssetCallbackId) {
        self.imp.remove_on_reducer("edit_asset", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `edit_asset`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_edit_asset {
    /// Set the call-reducer flags for the reducer `edit_asset` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn edit_asset(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_edit_asset for super::SetReducerFlags {
    fn edit_asset(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("edit_asset", flags);
    }
}
