// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::script_asset_type::ScriptAsset;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `scripts`.
///
/// Obtain a handle from the [`ScriptsTableAccess::scripts`] method on [`super::RemoteTables`],
/// like `ctx.db.scripts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scripts().on_insert(...)`.
pub struct ScriptsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ScriptAsset>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `scripts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ScriptsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ScriptsTableHandle`], which mediates access to the table `scripts`.
    fn scripts(&self) -> ScriptsTableHandle<'_>;
}

impl ScriptsTableAccess for super::RemoteTables {
    fn scripts(&self) -> ScriptsTableHandle<'_> {
        ScriptsTableHandle {
            imp: self.imp.get_table::<ScriptAsset>("scripts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ScriptsInsertCallbackId(__sdk::CallbackId);
pub struct ScriptsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ScriptsTableHandle<'ctx> {
    type Row = ScriptAsset;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ScriptAsset> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ScriptsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScriptsInsertCallbackId {
        ScriptsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ScriptsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ScriptsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScriptsDeleteCallbackId {
        ScriptsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ScriptsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ScriptAsset>("scripts");
    _table.add_unique_constraint::<String>("asset_path", |row| &row.asset_path);
}
pub struct ScriptsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ScriptsTableHandle<'ctx> {
    type UpdateCallbackId = ScriptsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ScriptsUpdateCallbackId {
        ScriptsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ScriptsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ScriptAsset>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ScriptAsset>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `asset_path` unique index on the table `scripts`,
/// which allows point queries on the field of the same name
/// via the [`ScriptsAssetPathUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scripts().asset_path().find(...)`.
pub struct ScriptsAssetPathUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ScriptAsset, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ScriptsTableHandle<'ctx> {
    /// Get a handle on the `asset_path` unique index on the table `scripts`.
    pub fn asset_path(&self) -> ScriptsAssetPathUnique<'ctx> {
        ScriptsAssetPathUnique {
            imp: self.imp.get_unique_constraint::<String>("asset_path"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ScriptsAssetPathUnique<'ctx> {
    /// Find the subscribed row whose `asset_path` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ScriptAsset> {
        self.imp.find(col_val)
    }
}
