on: 
  push:
    branches:
      - master
  workflow_dispatch:

name: Build and release

jobs:
  release:
    name: Release
    permissions: write-all

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
        
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: cargo fetch
        run: cargo fetch --target ${{ matrix.target }}
      - name: Release build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        env:
          NAME: morph
          TARGET: ${{ matrix.target }} 
          OS: ${{ matrix.os }} 
        run: |
            chmod +x ./.github/scripts/package.sh
            ./.github/scripts/package.sh
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: true
          files: "morph*"